### ISSUE TITLE
Subscription ID

### ISSUE THREAD

**Issue by amd006** [matthansen0/azure-openemr#3]
When I try the automated deployment, I get a "Subscription ID" not valid. I have the Standard Azure pay-as-you-go subscription. Do I need to set my subscription ID and login info to the yml?

Thanks in advance!

**Comment by matthansen0** [comment]
> When I try the automated deployment, I get a "Subscription ID" not valid. I have the Standard Azure pay-as-you-go subscription. Do I need to set my subscription ID and login info to the yml?
> 
> Thanks in advance!

Does the deployment validate? It should give you a drop-down list of your active subscriptions based on your user account on the template deploy page. Can you share a screenshot?

**Comment by amd006** [comment]
Thanks for your reply. However, I just went with the process below and had great success. Thanks again for your time.
Anup

https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/deploying-openemr-on-azure/ba-p/3741455
